## NUMPY

In [1]:
import numpy as np

##### Creating a numpy array using numpy.array() method

In [4]:
list=[4,5,6]
n=np.array(list)
n

array([4, 5, 6])

In [5]:
list1=[[1,2,3],[4,5,6],[7,8,9]]
n1=np.array(list1)
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
n2=np.array([1,2,3])
n2

array([1, 2, 3])

##### np.shape gives us the dimensions of the array

In [8]:
n1.shape

(3, 3)

##### np.arange(start,stop,steps) returns an array

In [10]:
n3=np.arange(0,30,2)
n3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

##### np.reshape(rows,cols) returns a new reshaped array

In [15]:
n4=n3.reshape(5,3) #it returns the resized array
n4

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

##### np.resize() does the resizing of array in-place

In [16]:
n3.resize(3,5) #does the resizing in-place
n3

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

##### np.ones((rows,cols),data_type) returns an array of ones

In [20]:
np.ones((2,3),int) 

array([[1, 1, 1],
       [1, 1, 1]])

##### np.zeros((rows,cols),data_type) returns an array of zeros

In [22]:
np.zeros((4,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
a=np.array([1,2,3]*3)
a.resize(3,3)
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [27]:
b=np.repeat([1,2,3],4)
b.resize(4,3)
b

array([[1, 1, 1],
       [1, 2, 2],
       [2, 2, 3],
       [3, 3, 3]])

##### np.vstack([arr1,arr2,....]) is used to stack all the arrays in the argument vertically

In [31]:
np.vstack([b, 2*b])

array([[1, 1, 1],
       [1, 2, 2],
       [2, 2, 3],
       [3, 3, 3],
       [2, 2, 2],
       [2, 4, 4],
       [4, 4, 6],
       [6, 6, 6]])

##### np.vhstack([arr1,arr2,....]) is used to stack all the arrays in the argument horizontally

In [33]:
np.hstack([b,b])

array([[1, 1, 1, 1, 1, 1],
       [1, 2, 2, 1, 2, 2],
       [2, 2, 3, 2, 2, 3],
       [3, 3, 3, 3, 3, 3]])

### Operations on arrays

In [34]:
x=np.array([1,2,3])
y=np.array([4,5,6])
x+y

array([5, 7, 9])

In [35]:
x-y

array([-3, -3, -3])

In [36]:
x*y

array([ 4, 10, 18])

In [39]:
x/y

array([0.25, 0.4 , 0.5 ])

In [40]:
x.dot(y) # x1*y1 + x2*y2+ x3*y3 , dot product

32

### In-built statistical methods

In [47]:
z=np.array([x,x*2,y])
z

array([[1, 2, 3],
       [2, 4, 6],
       [4, 5, 6]])

In [48]:
z.shape

(3, 3)

In [49]:
z.T
z.shape

(3, 3)

In [50]:
z.dtype

dtype('int32')

In [51]:
z.max()

6

In [52]:
z.min()

1

In [53]:
z.mean()

3.6666666666666665

In [54]:
z[2][0]

4

In [55]:
z.sum()

33

In [56]:
z.std()

1.699673171197595

In [57]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

### Slicing of arrays

In [61]:
arr=np.arange(36)
arr.resize((6,6))
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [62]:
arr[0]

array([0, 1, 2, 3, 4, 5])

In [63]:
arr[0][2]

2

In [65]:
arr[1][:4]

array([6, 7, 8, 9])

In [68]:
arr[1,4]

10

In [69]:
arr[:,:4]

array([[ 0,  1,  2,  3],
       [ 6,  7,  8,  9],
       [12, 13, 14, 15],
       [18, 19, 20, 21],
       [24, 25, 26, 27],
       [30, 31, 32, 33]])

In [70]:
arr[:4,-1]

array([ 5, 11, 17, 23])

In [71]:
arr[arr>30]

array([31, 32, 33, 34, 35])

In [73]:
arr2=arr
arr2[:3,:3]=0
arr2

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [75]:
arr

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [76]:
arr3=arr.copy()
arr3[5,:]=0
arr3

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [ 0,  0,  0,  0,  0,  0]])

In [77]:
arr

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])